### ISSUE TITLE
Not able to launch the training

### ISSUE THREAD

**Issue by stevinc** [godisboy/DRPAN#1]
I would like to try the architecture but at the time I launch the training, as indicated, I have the following error message:
  from ._crop_and_resize import lib as _lib, ffi as _ffi
ImportError: dynamic module does not define module export function (PyInit__crop_and_resize).
I looked for solutions but I didn't find anything useful.
I use archlinux as os, I tried both with python 3.7 and 3.6 but the error is the same, any suggestions?
Thanks.

**Comment by hologerry** [comment]
Same issue.

**Comment by hologerry** [comment]
Use the original RoIAlign code to build the ```_crop_and_resize.so``` file will solve this issue.
https://github.com/longcw/RoIAlign.pytorch

**Comment by jiangyufeng77** [comment]
The solution is as @hologerry said, Thank you.
